# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - devsupport-prod

on:
  push:
    branches:
      - live
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: 'devsupport-prod'    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production # this was 'dev' in the suggested file  
    steps:
    - uses: actions/checkout@v3 # this was '@master' in the suggested file 
    - name: Use Node.js ${{ env.NODE_VERSION }} # this was 'Set up Node.js version' in my original file 
      uses: actions/setup-node@v3 # this was 'v1' in the suggested file 
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      # this section was different in my original file  
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm prune --production
        npm install
        npm run build --if-present
        # npm run test --if-present
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'  # <-- this property wasn't in suggested file  
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_03A291D2682043ADB628A868CBAB02B2 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
  # For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
